### ISSUE TITLE
Add action log

### ISSUE THREAD

**Issue by raymondjxu** [ashtarcommunications/caselist#1]
It would be very helpful if openCaselist had a log on all caselists so it would be easier to track deletions and changes to team pages.

**Comment by ashtarcommunications** [comment]
All caselists already have a Recently Modified page. If you're talking about a more granular version of a history/change log on every individual team page, the database already has version tracking tables and the server side code already records data on all modifications. That is, the history is there, there's just not a UI to display it.

I am very unlikely to implement a UI for this in the near term. First, it's a lot of time I don't currently have, but secondly I used to get a lot of pushback when we had a version history interface on the old caselist. It turns out that a lot of people want to be able to permanently delete something from their page without it living in a publicly visible version history (e.g. think of accidentally uploading a new aff before you've read it, and having no way to scrub it from the public UI).

I'd be happy to consider PR's from others implementing different versions of this functionality depending on the specific proposal, but I'm going to close this issue for now as not something I will likely build personally.
